nines_user:
    roles:
        - ROLE_ADMIN
        - ROLE_BLOG_ADMIN
        - ROLE_CONTENT_ADMIN
        - ROLE_DC_ADMIN
        - ROLE_MEDIA_ADMIN
        - ROLE_USER_ADMIN
    after_login_route: homepage
    after_request_route: homepage
    after_reset_route: nines_user_security_login
    after_logout_route: homepage
