<?php

namespace AppBundle\Repository;

/**
 * ArtworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkRepository extends \Doctrine\ORM\EntityRepository
{
}
