<?php

namespace AppBundle\Repository;

/**
 * ArtworkTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
