<?php

namespace AppBundle\Repository;

/**
 * ArtworkContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkContributionRepository extends \Doctrine\ORM\EntityRepository {
    
}
