<?php

namespace AppBundle\Repository;

/**
 * ArtworkMediaFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkMediaFileRepository extends \Doctrine\ORM\EntityRepository {
    
}
