<?php

namespace AppBundle\Repository;

/**
 * ArtworkRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
