<?php

namespace AppBundle\Repository;

/**
 * ArtworkCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
