<?php

namespace AppBundle\Repository;

/**
 * MediaFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaFileRepository extends \Doctrine\ORM\EntityRepository {

    public function searchQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->distinct();
        $qb->innerJoin('e.metadataFields', 'f');
        $qb->orWhere("MATCH_AGAINST(f.value) AGAINST (:q BOOLEAN) > 0");
        $qb->setParameter('q', $q);
        return $qb->getQuery();
    }

}
