<?php

namespace AppBundle\Repository;

/**
 * MediaFileCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaFileCategoryRepository extends \Doctrine\ORM\EntityRepository {
    
}
