<?php

namespace AppBundle\Repository;

/**
 * MediaFileFieldRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaFileFieldRepository extends \Doctrine\ORM\EntityRepository {
}
