<?php

namespace AppBundle\Repository;

/**
 * MediaFileTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaFileTypeRepository extends \Doctrine\ORM\EntityRepository {
    
}
