<?php

namespace AppBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository {

    public function searchQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->where("MATCH_AGAINST(e.fullname, e.biography) AGAINST(:q 'BOOLEAN') > 0");
        $qb->setParameter('q', $q);
        return $qb->getQuery();
    }

}
