<?php

namespace AppBundle\Repository;

/**
 * ProjectTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
