<?php

namespace AppBundle\Repository;

/**
 * ProjectCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectCategoryRepository extends \Doctrine\ORM\EntityRepository {
    
}
