<?php

namespace AppBundle\Repository;

/**
 * ProjectContributionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectContributionRepository extends \Doctrine\ORM\EntityRepository {
}
