<?php

namespace AppBundle\Repository;

/**
 * ProjectPageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectPageRepository extends \Doctrine\ORM\EntityRepository {
}
