<?php

namespace AppBundle\Repository;

/**
 * ProjectRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
