<?php

namespace AppBundle\Repository;

/**
 * VenueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenueRepository extends \Doctrine\ORM\EntityRepository
{
}
