<?php

namespace AppBundle\Repository;

/**
 * VenueTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenueTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
