<?php

namespace AppBundle\Repository;

/**
 * VenueCategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenueCategoryRepository extends \Doctrine\ORM\EntityRepository {
}
