nines_blog:
    resource: '@NinesBlogBundle/Controller'
    prefix: '%router.request_context.base_url%'

nines_dc:
    resource: '@NinesDublinCoreBundle/Controller'
    prefix: '%router.request_context.base_url%/dublin_core'

nines_editor:
    resource: '@NinesEditorBundle/Controller'
    prefix: '%router.request_context.base_url%/editor'

nines_user:
    resource: '@NinesUserBundle/config/routes.yaml'
    prefix: '%router.request_context.base_url%'

controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: '%router.request_context.base_url%'

kernel:
    resource: ../src/Kernel.php
    type: attribute
    prefix: '%router.request_context.base_url%'